### ISSUE TITLE
Support for Model 1473

### ISSUE THREAD

**Issue by olgadagod** [diablodale/jit.openni#32] opened 2014-05-01 18:57 UTC
Hello,
I've been using jit.openni for a while now, and recently when my kinect broke (the wire broke), I purchased a new one that said it was 1414 but was actually 1473. Do I need to return this? Is there support for the model with jit.openni? It is semi-urgent!
Sharmi

**Comment by diablodale** [comment] 2014-05-02 11:43
closing as a duplicate of https://github.com/diablodale/jit.openni/issues/31

**Closed as completed by diablodale** 2014-05-02 11:43 UTC
